# Generated by Django 4.1.1 on 2023-05-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_id',
            new_name='stripe',
        ),
    ]
