# Generated by Django 4.1.1 on 2023-05-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=60)),
                ('postalCode', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
