# Generated by Django 4.1.1 on 2023-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.CharField(default='U_iuwV8CfnrSnUeeaAiaF', editable=False, max_length=50, unique=True),
        ),
    ]
