# Generated by Django 4.1.1 on 2023-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.CharField(default='FJfB3ogGmZeZH3bGgPe_e', editable=False, max_length=50, unique=True),
        ),
    ]
