# Generated by Django 4.1.1 on 2023-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.CharField(default='kIAr47-gvFLlejENLC9oX', editable=False, max_length=50, unique=True),
        ),
    ]
