# Generated by Django 4.1.1 on 2023-05-01 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('dfc6ee86-bff8-4b41-b026-82099e0f9cc4'), editable=False, unique=True),
        ),
    ]
