# Generated by Django 4.1.1 on 2023-05-01 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e69b8c60-0404-4d3d-b13b-8bddb4d5f1f8'), editable=False, unique=True),
        ),
    ]
