# Generated by Django 4.1.1 on 2023-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
