# Generated by Django 4.1.1 on 2023-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation_id',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
