# Generated by Django 4.1.1 on 2023-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cartitem_variation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation_id',
            field=models.IntegerField(blank=True),
        ),
    ]
