# Generated by Django 4.1.1 on 2023-07-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariation'),
        ('cart', '0014_alter_cartitem_variation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
