# Generated by Django 4.1.1 on 2023-07-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
