# Generated by Django 4.1.1 on 2023-05-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
