# Generated by Django 4.1.1 on 2023-07-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0019_alter_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(choices=[(0, 'public'), (1, 'membership')])),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='downloads/')),
                ('other', models.JSONField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(choices=[(0, 'public'), (1, 'membership')])),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(choices=[(0, 'public'), (1, 'membership')])),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
