# Generated by Django 4.1.1 on 2023-07-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmembership',
            old_name='product',
            new_name='product_id',
        ),
    ]
