# Generated by Django 4.1.1 on 2023-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_product_productmembership_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmembership',
            name='preview',
            field=models.ImageField(blank=True, upload_to='media/members/'),
        ),
        migrations.AddField(
            model_name='productmembership',
            name='preview',
            field=models.ImageField(blank=True, upload_to='media/members/'),
        ),
        migrations.AddField(
            model_name='videomembership',
            name='preview',
            field=models.ImageField(blank=True, upload_to='media/members/'),
        ),
    ]
