# Generated by Django 4.1.1 on 2023-07-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membership_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
    ]
