# Generated by Django 4.1.1 on 2023-07-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_membership_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.FloatField(default=9.99),
            preserve_default=False,
        ),
    ]
