# Generated by Django 4.1.1 on 2023-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_membership_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
