# Generated by Django 4.1.1 on 2023-05-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productdowload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdowload',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
