# Generated by Django 4.1.1 on 2023-06-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productdowload_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdowload',
            name='published',
        ),
    ]
