# Generated by Django 4.1.1 on 2023-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
