# Generated by Django 4.1.1 on 2023-07-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_stock_productvariation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
