# Generated by Django 4.1.1 on 2023-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image')], default='image', max_length=5),
        ),
    ]
